# pixi.toml
[project]
channels = ["conda-forge"]
platforms = ["linux-64","osx-64","osx-arm64","win-64"]

[dependencies]
python = ">=3.9,<3.13"
numpy = ">=1.22"
scipy = ">=1.9"
numexpr = ">=2.8"
pip = "*"

[pypi-dependencies]
# Pull in our package editable with dev extras so pytest is available
nbmf-mm = { path = ".", editable = true, extras = ["dev"] }
pytest = ">=7"
pytest-cov = ">=4"
ruff = ">=0.5"

[tasks]
test = "pytest -q"
lint = "ruff check src tests"
