# pixi.toml — dev environment & tasks for NBMF-MM
[project]
name = "nbmf-mm-dev"
version = "0.0.0"
description = "Dev environment for NBMF-MM"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.9,<3.13"
numpy = "*"
scipy = "*"

[pypi-dependencies]
nbmf-mm = { path = ".", editable = true }
scikit-learn = "*"
numexpr = "*"
numba = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
mypy = "*"
uv = "*"

[tasks]
test = "pytest -q"
lint = "ruff check ."
fmt = "ruff format ."
types = "mypy --ignore-missing-imports src/nbmf_mm"
build = "uv build"
publish = "uv publish"
