"""
NBMF-MM: Bernoulli Mean-Parameterized Non-negative Binary Matrix Factorization with Majorization-Minimization

Public API for nbmf_mm.

A scikit-learn compatible implementation of Bernoulli mean-parameterized
Non-negative Binary Matrix Factorization using Majorization-Minimization.
"""

from __future__ import annotations

# Public API
from .estimator import NBMF, BernoulliNMF_MM  # noqa: F401

# Version: prefer setuptools_scm-generated file, otherwise fall back to metadata
try:  # generated by setuptools_scm if [tool.setuptools_scm.write_to] is set
    from ._version import version as __version__  # type: ignore[attr-defined]
except Exception:
    try:
        from importlib.metadata import version as _pkg_version  # Python 3.8+
    except Exception:  # pragma: no cover
        __version__ = "0+unknown"  # last-ditch fallback
    else:  # pragma: no cover
        try:
            __version__ = _pkg_version("nbmf-mm")
        except Exception:
            __version__ = "0+unknown"

__all__ = ["NBMF", "BernoulliNMF_MM", "__version__"]
