name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  id-token: write  # required for Trusted Publishing (OIDC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install -U build
      - run: python -m build

      # --- PyPI publish with OIDC (Trusted Publishing) if no token is set ---
      - name: Publish to PyPI (OIDC)
        if: ${{ secrets.PYPI_API_TOKEN == '' || secrets.PYPI_API_TOKEN == null }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

      # --- Fallback: PyPI publish using API token if provided ---
      - name: Publish to PyPI (API token)
        if: ${{ secrets.PYPI_API_TOKEN != '' && secrets.PYPI_API_TOKEN != null }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/
          skip-existing: true
